### ISSUE TITLE
What is the format of distribution file for dsdgen

### ISSUE THREAD

**Issue by rucjrliu** [microsoft/dsb#3]
DSB is really creative and useful. May I ask What the format of distribution file for dsdgen is ?

Advanced Options

DELIMITER =  <s>         -- use <s> as output field separator
DISTRIBUTIONS =  <s>     -- read distributions from file <s>
FORCE =  [Y|N]           -- over-write data files without prompting
SUFFIX =  <s>            -- use <s> as output file suffix
TERMINATE =  [Y|N]       -- end each record with a field delimiter
VCOUNT =  <n>            -- set number of validation rows to be produced
VSUFFIX =  <s>           -- set file suffix for data validation
RNGSEED =  <n>           -- set RNG seed

i.e. What should "DISTRIBUTIONS =  <s>     -- read distributions from file <s>" the file <s> contain?

**Comment by bailud** [comment]
> 

Hi @rucjrliu , could you try if you can modify the example JSON config for generating the workload (https://github.com/microsoft/dsb/blob/main/scripts/workload_config.json)?

**Comment by rucjrliu** [comment]
Yes. So, is the format of "distribution file" for data generation same as this "workload_config.json" for workload generation ?

**Comment by bailud** [comment]
> Yes. So, is the format of "distribution file" for data generation same as this "workload_config.json" for workload generation ?

Could you see if you can follow the script ./scripts/generate_workload.py to generate the workload?
