### ISSUE TITLE
The choice -param_dist doesn't work in Ubuntu22.04 

### ISSUE THREAD

**Issue by EvagelineFEI** [microsoft/dsb#7]
Hi Bailu~
when I run 
`./dsqgen -input /my_path/dsb/query_templates_pg/agg_queries/templates.lst -OUTPUT_DIR /my_path/dsb_workload/tmp -directory /my_path/dsb/query_templates_pg/agg_queries -dialect postgres -param_dist normal -rngseed 997` in my Ubuntu22.04
I got 
`ERROR: File 'my_path/dsb/querynormal/query013.tpl' not found`
After I remove the "param_dist", it works ok for me. But I am not sure whether the parameter is necessary for me cause I don't exactly understand what role "param_dist" plays(which is not mentioned both in README or the DSB paper, can you explain for me? Thanks so much)

**Comment by bailud** [comment]
Hi @EvagelineFEI, Thanks for the feedback. The param_dist is used for specifying the distribution of the parameters. By default, the parameters will follow uniform distribution. If this works for you, you can safely discard the param_dist parameter. I will take a look at the error and fix it later.

**Comment by EvagelineFEI** [comment]
Ok, thanks so much！ @bailud  And I complie the code by adding -fcommon to makefile which is mentioned in (https://github.com/microsoft/dsb/pull/5/commits/42896f5647c2da79961d24f634843e603d699729)；It's really helpful for users who want to use this benchmark in Linux environment.

**Comment by EvagelineFEI** [comment]
Hi! And I find that some parameters which work in original TPCH-DS seem to not work here, like "-scale";
When I run 
`./dsqgen -input mypath/dsb/query_templates_pg/multi_block_queries/templates.lst -output_dir mypath/dsb_workload/multi -streams 10 -directory mypath/dsb/query_templates_pg/multi_block_queries -dialect postgres -scale 1 -rngseed 997`
I got 
`ERROR: Open failed on 'my_path/dsb/query_templates_pg/multi_block_queri1'
my_path/dsb/query_templates_pg/multi_block_queri1: No such file or directory`

**Comment by bailud** [comment]
> Hi! And I find that some parameters which work in original TPCH-DS seem to not work here, like "-scale"; When I run `./dsqgen -input mypath/dsb/query_templates_pg/multi_block_queries/templates.lst -output_dir mypath/dsb_workload/multi -streams 10 -directory mypath/dsb/query_templates_pg/multi_block_queries -dialect postgres -scale 1 -rngseed 997` I got `ERROR: Open failed on 'my_path/dsb/query_templates_pg/multi_block_queri1' my_path/dsb/query_templates_pg/multi_block_queri1: No such file or directory`

Hi @EvagelineFEI, the error message indicates that there is some issue with the path of the files. It may be related to the previous issue. I will take a look over the weekend.

**Comment by bailuding** [comment]
> Hi! And I find that some parameters which work in original TPCH-DS seem to not work here, like "-scale"; When I run `./dsqgen -input mypath/dsb/query_templates_pg/multi_block_queries/templates.lst -output_dir mypath/dsb_workload/multi -streams 10 -directory mypath/dsb/query_templates_pg/multi_block_queries -dialect postgres -scale 1 -rngseed 997` I got `ERROR: Open failed on 'my_path/dsb/query_templates_pg/multi_block_queri1' my_path/dsb/query_templates_pg/multi_block_queri1: No such file or directory`

Hi @EvagelineFEI , I just realized that the binary you use is the one that generates the queries, not the data. The binary to generate the data is dsdgen. Could you double check and try dsdgen?

**Comment by bailud** [comment]
> Hi! And I find that some parameters which work in original TPCH-DS seem to not work here, like "-scale"; When I run `./dsqgen -input mypath/dsb/query_templates_pg/multi_block_queries/templates.lst -output_dir mypath/dsb_workload/multi -streams 10 -directory mypath/dsb/query_templates_pg/multi_block_queries -dialect postgres -scale 1 -rngseed 997` I got `ERROR: Open failed on 'my_path/dsb/query_templates_pg/multi_block_queri1' my_path/dsb/query_templates_pg/multi_block_queri1: No such file or directory`

Hi @EvagelineFEI , I just realized that the binary you use is the one that generates the queries, not the data. The binary to generate the data is dsdgen. Could you double check and try dsdgen?

**Comment by bailud** [comment]
> Hi Bailu~ when I run `./dsqgen -input /my_path/dsb/query_templates_pg/agg_queries/templates.lst -OUTPUT_DIR /my_path/dsb_workload/tmp -directory /my_path/dsb/query_templates_pg/agg_queries -dialect postgres -param_dist normal -rngseed 997` in my Ubuntu22.04 I got `ERROR: File 'my_path/dsb/querynormal/query013.tpl' not found` After I remove the "param_dist", it works ok for me. But I am not sure whether the parameter is necessary for me cause I don't exactly understand what role "param_dist" plays(which is not mentioned both in README or the DSB paper, can you explain for me? Thanks so much)

I took another look at the command you use. Could you use -template with the template file name instead of using -input and see if this works?

**Comment by bailud** [comment]
I will close this issue since this is due to the misuse of the commands.

**Comment by EvagelineFEI** [comment]
Ok, thanks so mutch! I ll check!

**Comment by EvagelineFEI** [comment]
@bailud Thanks so much! I ll double check
